sonar.projectKey=armandocorrea_node-js-fc
sonar.organization=armandocorrea
sonar.projectName=node-js-fc
sonar.projectVersion=1.0

# Código fonte
sonar.sources=.

# Diretório de testes
sonar.tests=__tests__

# Relatório de cobertura Jest
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8